<?php

/**
 * @file
 * Integration module for NYS Global Navigation.
 * Defines two blocks, NYS Global Navigation Header and NYS Global Navigation
 *   Footer.  Can also be integrated directly into a theme.
 * See:  https://github.com/ny/global-navigation
 */

/**
 * Implements hook_menu().
 */
function nys_global_nav_menu() {
  $items['admin/config/user-interface/nys-global-nav'] = array(
    'title' => 'NYS Global Navigation',
    'description' => 'Configure NYS Global Navigation Header and Footer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nys_global_nav_admin_settings'),
    'access arguments' => array('administer nys global nav'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nys_global_nav.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function nys_global_nav_block_info() {
  $blocks = array(
    'nys_global_nav_header' => array(
      // The name that will appear in the block list.
      'info' => t('NYS Global Navigation Header'),
      // Disable caching in MVP.
      'cache' => DRUPAL_NO_CACHE,
    ),
    'nys_global_nav_footer' => array(
      // The name that will appear in the block list.
      'info' => t('NYS Global Navigation Footer'),
      // Disable caching in MVP.
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nys_global_nav_block_view($delta = '') {
  switch ($delta) {
    case 'nys_global_nav_header':
      // set block subject and content
      $block['subject'] = t('NYS Global Navigation Header');
      $block['content'] = nys_global_nav_header();

      return $block;
    case 'nys_global_nav_footer':
      // set block subject and content
      $block['subject'] = t('NYS Global Navigation Footer');
      $block['content'] = nys_global_nav_footer();

      return $block;
  }
}

/**
 * Implements hook_page_build().
 *
 * Add uNav header and footer to the page_top and page_bottom regions
 * automatically if corresponding Drupal variable nys_global_nav_%_auto is TRUE.
 * But don't add uNav if on an administrative page.
 */
function nys_global_nav_page_build(&$page) {
  // Performance: Skip this entirely for AJAX requests or if on administrative
  //   page.  AJAX code from admin_menu module, seemed like a good idea.
  if ((strpos($_GET['q'], 'js/') === 0) || path_is_admin(current_path())) {
    return;
  }
  /*********************************************************************
   * Debugging code to be removed
   */
  $test = drupal_get_path('module', 'color');
  /***  End of Debugging Code  ***/
  if (variable_get('nys_global_nav_header_auto', FALSE)) {
    $page['page_top']['nys_global_nav'] = _nys_global_nav_header();
  }
  if (variable_get('nys_global_nav_footer_auto', FALSE)) {
    $page['page_bottom']['nys_global_nav'] = _nys_global_nav_footer();
  }
}

/**
 * Implements hook_theme().
 */
function nys_global_nav_theme() {
  return array(
    'nys_global_nav_header' => array(
        'template' => 'nys-global-nav-header',
        'variables' => array(
          'header_menu_name' => NULL,
        ),
    ),
    'nys_global_nav_footer' => array(
        'template' => 'nys-global-nav-footer',
        'variables' => array(),
    ),
    'nys_global_nav_menu' => array(
      'variables' => array(
        'menu_name' => NULL,
     ),
    ),
    'nys_global_nav_menu_item' => array(
      'variables' => array(
        'element' => NULL,
        'properties' => NULL,
      ),
    ),
    'nys_global_nav_menu_item_link' => array(
      'variables' => array(
        'menu_item' => NULL,
        'link_options' => NULL,
      ),
    ),
  );
}


/**
 * Implements hook_permission().
 */
function nys_global_nav_permission() {
  return array(
    'administer nys global nav' => array(
      'title' => t('Administer NYS Global Navigation'),
    ),
  );
}


/**
 * Implements hook_help().
 */
function nys_global_nav_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/modules#description':
      $output .= t('Integrate NYS Global Navigation onto your Drupal site.');
      break;

    case 'admin/config/user-interface/nys-global-nav':
      // $output .= t('<p>Block-specific Superfish settings could be found at !link</p>', array('!link' => l(t('Blocks management'), 'admin/structure/block')));
      break;
  }
  return $output;
}

/**
 * Non-hook function to generate header block content.
 * @return
 * Raw html content suitable for printing in theme.
 */
function nys_global_nav_header() {
  $header = theme('nys-global-nav-header');
  return $header;
}

/**
 * Non-hook function to generate footer block content.
 * @return
 * Raw html content suitable for printing in theme.
 */
function nys_global_nav_footer() {
  $footer = theme('nys-global-nav-footer');
  return $footer;
}

/**
 * Non-hook function to generate header block content.
 *
 * @return array
 * Render array element that defines the header.
 * Includes the CSS and JS to be included on the page.
 */
function _nys_global_nav_header() {
  $resources_location = nys_global_nav_get_path('nys_global_nav') . '/source' ;
  $header = array(
    '#weight' => -950,
    '#header_menu_name' => variable_get('nys_global_nav_header_menu', ''),
    '#theme' => 'nys_global_nav_header',
    '#attached' => array(
      'css' => array(
        $resources_location . '/css/nys-brand/' . variable_get('nys_global_nav_agency_color', 'administration') . '.css',
        $resources_location . '/css/nys-global-nav.css',
        $resources_location . '/css/nys-global-nav-fonts.css',
      ),
      'js' => array(
        $resources_location . '/js/nys-global-nav-header.js',
      )
    ),
  );
  return $header;
}

/**
 * Non-hook function to generate footer block content.
 *
 * @return array
 * Render array element that defines the footer.
 */
function _nys_global_nav_footer() {
  $footer = array(
    '#weight' => 950,
    '#theme' => 'nys_global_nav_footer',
  );
  return $footer;
}

/**
 * Theme function to allow any menu tree to be themed for the NYS Global Navigation.
 * Code patterned/copied from drupal.org/project/superfish and adapted.
 */
function theme_nys_global_nav_menu($variables){
  global $user, $language;

  // $id = $variables['id'];
  $menu_name = $variables['menu_name'];
  // $mlid = $variables['mlid'];

  $menu = menu_tree_all_data($menu_name);

  if (function_exists('i18n_menu_localize_tree')) {
    $menu = i18n_menu_localize_tree($menu);
  }

  return;
}

/**
 * Theme a menu item link.
 *
 * @param $variables
 *   An array of variables containing:
 *    - menu_item: The menu item array.
 *    - link_options: An array of link options.
 *
 * @ingroup themeable
 */
function theme_nys_global_nav_menu_item_link($variables) {
  $menu_item = $variables['menu_item'];
  $link_options = $variables['link_options'];
  return l($menu_item['link']['title'], $menu_item['link']['href'], $link_options);
}

/**
 * Helper function to get library paths.
 */
function nys_global_nav_get_path($library = 'nys_global_nav') {
  $directory = '';
  // Ensure the Libraries API module is installed.
  if (module_exists('libraries') && function_exists('libraries_get_path')) {
    $directory = libraries_get_path($library);
  }
  // Otherwise use the default directory.
  elseif (file_exists('profiles/' . drupal_get_profile() . '/libraries/' . $library)) {
    $directory = 'profiles/' . drupal_get_profile() . '/libraries/' . $library;
  }
  if (empty($directory)) {
    $directory = 'sites/all/libraries/' . $library;
  }
  return $directory;
}
