<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
//Note:  Do not include the opening and closing PHP tags when you copy this code

function my_special_debug($debugmessage){
  print('<h3 style="display:block!important;">' . $debugmessage . '</h3>');
}
// settings for the stylesheet to use for the global header. It's called theme here because we can't decide whether we're in clusters or what.
// menu
/**
 * Implements hook_menu().
 */
function nys_global_nav_menu() {
  $items = array();
  $items['admin/config/content/nys_global_nav'] = array(
    'title' => 'NYS Global Header',
    'description' => 'Configuration for NYS Global Header module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nys_global_nav_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
// page
function nys_global_nav_form($form, &$form_state) {
  $form['nys_global_nav_theme'] = array(
    '#type' => 'select',
    '#title' => t('Theme'),
    '#default_value' => variable_get('nys_global_nav_theme', 'administration'),
    '#options' => array(
      'administration' => t('Administration'), 
      'business' => t('Business'), 
      'education' => t('Education'), 
      'health-and-human-services' => t('Health and Human Services'), 
      'local-and-regional-authorities' => t('Local and Regional Authorities'), 
      'public-safety' => t('Public Safety'), 
      'recreation-and-environment' => t('Recreation and Environment'), 
      'statewide-elected-officials' => t('Statewide Elected Officials'), 
      'transportation-and-utilities' => t('Transportation and Utilities'),
    ),
    '#description' => t("Select theme to display the correct colors for your agency."),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

// include selected navigation theme
$nys_global_nav_theme_stylesheet =  '/global-nav-resources/css/nys-brand/' . variable_get("nys_global_nav_theme", 'administration') . '.css';
drupal_add_css(drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_stylesheet);




// include javascript
//$nys_global_nav_theme_js =  '/global-nav-resources/js/nys-global-nav-header.js';
//drupal_add_js(drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_js);
//my_special_debug(drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_stylesheet);
//my_special_debug(drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_js);


//my_special_debug(path_is_admin(current_path()));
// fill a variable with the current header theme
// include the proper css. 
// TODO: Should the path to the css be a module variable?
// I think this is causing a problem: https://www.drupal.org/node/1115980
// include the js file only if we're not on an administration page.
//if (!path_is_admin(current_path())) {
 // 
 // drupal_add_css(drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_stylesheet);
  // $nys_global_nav_theme_js =  '/global-nav-resources/js/nys-global-nav-header.js';
  // drupal_add_js(drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_js);
  // $nys_global_nav_theme_js_path = drupal_get_path('module', 'nys_global_nav') . $nys_global_nav_theme_js;
  // drupal_add_js($nys_global_nav_theme_js_path, 'file');
//}
//$thispath = current_path();
//if (!(path_is_admin($thispath))) {
//  my_special_debug("not admin");
//} else {
//  my_special_debug("admin");
//}